LAB 16 – Applied Data Manipulation Using NumPy

In [1]:
import numpy as np

# 1. Temperature Monitoring
temps = np.array([32, 34, 31, 29, 35, 33, 30]) 
print("Temperature Array:", temps)
print("Shape:", temps.shape)   
print("Size:", temps.size)   
print("Dimensions:", temps.ndim)  # number of dimensions
print("Data Type:", temps.dtype)  # type of elements

print("-" * 40)

Temperature Array: [32 34 31 29 35 33 30]
Shape: (7,)
Size: 7
Dimensions: 1
Data Type: int32
----------------------------------------


In [2]:
# 2. Class Attendance
# -----------------------------
attendance = np.array([25, 28, 26, 27, 24])
print("Average Attendance:", np.mean(attendance))

print("-" * 40)


Average Attendance: 26.0
----------------------------------------


In [3]:
# 3. Exam Marks
# -----------------------------
marks = np.array([45, 78, 88, 60, 92, 55, 73, 81])
print("Marks between 3rd and 6th index:", marks[3:7])  # slicing

print("-" * 40)


Marks between 3rd and 6th index: [60 92 55 73]
----------------------------------------


In [4]:
# 4. Temperature Readings
# -----------------------------
temps_readings = np.array([32.5, 33.0, 31.8, 30.2, 29.5, 30.0, 28.9])
print("Temperatures (Day 2, 4, 6):", temps_readings[[1, 3, 5]])  # indexing multiple

print("-" * 40)

Temperatures (Day 2, 4, 6): [33.  30.2 30. ]
----------------------------------------


In [5]:
# 5. Product Prices
# -----------------------------
prices = np.array([120, 340, 560, 430, 220, 310])
print("First 3 products:", prices[:3])         
print("Last 2 products:", prices[-2:])         # last two using negative indexing

print("-" * 40)

First 3 products: [120 340 560]
Last 2 products: [220 310]
----------------------------------------


In [6]:
# 6. Seating Arrangement
roll_numbers = np.arange(1, 13)  # 1 to 12
seating = roll_numbers.reshape(3, 4)  # reshape into 3x4
print("Seating Arrangement (3x4):\n", seating)

print("-" * 40)

Seating Arrangement (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----------------------------------------


In [7]:
# 7. Matrix Conversion
matrix = np.arange(1, 17).reshape(4, 4)  # 1 to 16 in 4x4
print("4x4 Matrix:\n", matrix)
print("Second Row:", matrix[1])  

print("-" * 40)

4x4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Second Row: [5 6 7 8]
----------------------------------------


In [8]:
# 8. Monthly Rainfall
rainfall = np.array([110, 98, 120, 87, 130, 95])
sorted_rainfall = np.sort(rainfall)  # sort values
print("Sorted Rainfall:", sorted_rainfall)
print("Highest Rainfall:", sorted_rainfall[-1])  # last element is highest

print("-" * 40)

Sorted Rainfall: [ 87  95  98 110 120 130]
Highest Rainfall: 130
----------------------------------------


In [9]:
# 9. Merging Departments
science = np.array([1, 2, 3, 4])
arts = np.array([5, 6, 7])
merged = np.concatenate((science, arts))  # merge arrays
print("Merged Departments:", merged)

print("-" * 40)

Merged Departments: [1 2 3 4 5 6 7]
----------------------------------------


In [10]:
# 10. Profit Calculation
revenue = np.array([2000, 3000, 4000])
expenses = np.array([1500, 2000, 2500])
profit = revenue - expenses  # element-wise subtraction
print("Profit for each month:", profit)

Profit for each month: [ 500 1000 1500]
